/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model(props) {
  const { nodes, materials } = useGLTF('/models/ImageToStl.com_uploads_files_4251889_blend_shoesample.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[1.934, 0, -0.493]} rotation={[Math.PI, 0, Math.PI]} scale={1.231}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brand_tag007.geometry}
          material={materials['imagetexture green']}
          position={[0.07, 0.028, -0.072]}
          scale={0.727}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BUBBLE007.geometry}
          material={materials['Bubble green']}
          position={[0.07, -0.074, 0.049]}
          scale={0.812}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.outer_design007.geometry}
          material={materials['leather green']}
          position={[0.07, -0.038, 0.049]}
          scale={0.812}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.outer_dsign_thread007.geometry}
          material={materials['thread green']}
          position={[0.07, -0.039, 0.049]}
          scale={0.812}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shoe_pad007.geometry}
          material={materials['shoe pad.001']}
          position={[0.07, -0.019, 0.049]}
          scale={[0.758, 0.812, 0.76]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shoelace_area_design007.geometry}
          material={materials['leather top green']}
          position={[0.07, -0.038, 0.049]}
          scale={0.812}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shoelace_support007.geometry}
          material={materials['outer original.004 green']}
          position={[0.07, -0.103, 0.036]}
          rotation={[0.086, 0, 0]}
          scale={0.812}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SHOELACE007.geometry}
          material={materials['shoelace green']}
          position={[0.31, 0.089, 0.655]}
          scale={0.812}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sock_inner007.geometry}
          material={materials['cloth inside green']}
          position={[0.07, -0.038, 0.049]}
          scale={0.812}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sock_outer007.geometry}
          material={materials['outer original green']}
          position={[0.07, -0.038, 0.049]}
          scale={[0.795, 0.812, 0.812]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sole_2_main028.geometry}
          material={materials['sole higher green']}
          position={[0.07, -0.038, 0.049]}
          scale={0.812}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sole_2_main029.geometry}
          material={materials['sole green']}
          position={[0.07, -0.038, 0.049]}
          scale={0.812}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sole_2_main030.geometry}
          material={materials['sole green']}
          position={[0.066, -0.046, 0.087]}
          scale={0.812}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sole_2_pattern007.geometry}
          material={materials['sole green']}
          position={[0.07, -0.038, 0.049]}
          scale={0.812}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sole_back__lining007.geometry}
          material={materials['sole bubble lining green']}
          position={[0.07, -0.038, 0.049]}
          scale={[0.797, 0.812, 0.812]}
        />
      </group>
    </group>
  )
}
export default Model
useGLTF.preload('/models/ImageToStl.com_uploads_files_4251889_blend_shoesample.glb')

